configuration:
  dependencies:
  - "mvn://org.codehaus.groovy:groovy-all:pom:2.5.8"

flows:
  test-groovy-simple:
    - script: groovy 
      body: |
        def clusterId = "c-12"
        def map = [ 
          clusters:  [
            "c-12" : [
              info1: "info1data",
              info2: "info2data"

            ]  
          ]
        ]
        println("map-${map}")
        println("map-${map.clusters}")
        println("map-${map.clusters.get(clusterId)}")
        println("map-${map.clusters.get(clusterId)}")
        def workerMap =  [
                "worker" : [ min :  1, max : 1, sku : "n1-standard-8", cpu : "32", mem : "120GB" ]
          ]
        def istioMap =  [
                "istio" : [ min :  1, max : 1, sku : "n1-standard-8",cpu : "32", mem : "120GB" ]
          ]
        def gkeConfigMap = [
            "small-single-tenant":  [
              cluster_profile: [ workerMap, istioMap ],
              clusters : [
                (clusterId): [
                  region : region,
                  subnet_name: subnetName,
                  pod_range: podRange,
                  service_range : serviceRange,
                  master_range: "10.240.48.0/28",
                  master_authorized_range: masterAuthorizedRange,
                  svc_account_key : svcAccountKey,
                  svc_account : svcAccount,
                  vpc_name : vpcName,
                  service_project: serviceProject
                ]
              ]
            ]
        println("map-${gkeConfigMap}")   
    - log: "done"
  
triggers:
- manual:
    name: test-groovy-simple
    entryPoint: test-groovy-simple
