flows:
  test-groovy-simple:
    - script: groovy 
      body: |
        def clusterId = "c-12"
        def map = [ clusterId ]
        println("map-${map}")
    - log: "done"
  
triggers:
- manual:
    name: test-groovy-simple
    entryPoint: test-groovy-simple
