configuration:
  dependencies:
  - "mvn://org.codehaus.groovy:groovy-all:pom:2.5.8"

flows:
  test-groovy-simple:
    - script: groovy 
      body: |
        def clusterId = "c-12"
        def map = [ 
          clusters:  [
            "c-12" : [
              info1: "info1data",
              info2: "info2data"

            ]  
          ]
        ]
        println("map-${map}")
        println("map-${map.clusters}")
        println("map-${map.clusters.get(clusterId)}")
    - log: "done"
  
triggers:
- manual:
    name: test-groovy-simple
    entryPoint: test-groovy-simple
